name: CI

# Define the events that trigger the workflow
on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the environment for the job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Clone the repository into the workflow

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Set up the specified version of Node.js
        with:
          node-version: '18'  # Specify the version of Node.js to use

      - name: Install dependencies
        run: npm install  # Install the project's dependencies defined in package.json

      - name: Load environment variables
        run: cp .env.test .env  # Copy the .env.test file to .env to load environment variables for testing

      - name: Run tests
        run: npm test  # Run the test suite to ensure code correctness
        env:
          REACT_APP_TMDB_API_KEY: ${{ secrets.REACT_APP_TMDB_API_KEY }}  # TMDB API KEY given to github from Secret
